type Dict = Record<string, string>;

const EN: Dict = {
  in_band: "In comfort band",
  cool_edge: "Cool edge of band",
  warm_edge: "Warm edge of band",
  below: "Below comfort band",
  above: "Above comfort band",
  unknown: "No reading",
  preheating: "Pre-heating",
  coasting: "Coasting",
  window: "Window open",
  window_auto: "Window (auto)",
  bypass: "Window detection off",
  eco: "Eco",
  comfort: "Comfort",
  boost: "Boost",
  away: "Away",
  failure: "Heating failure",
  learning: "Learning",
  shadow: "Shadow active",
  setpoint: "Setpoint",
  no_entity: "Select a Poise thermostat entity.",
  min_left: "min",
  no_system: "Select the Poise System sensor.",
  sys_title: "Poise System",
  demand_on: "Boiler demand",
  demand_off: "No demand",
  frost: "Frost override",
  zones: "zones",
  heating_n: "heating",
  flow: "Flow",
  shed: "shed",
  shadow_would: "would",
  update_msg: "New Poise card version available — reload to update.",
  reload: "Reload",
  details: "Show details",
  temperature: "Temperature",
  humidity: "Humidity",
  co2: "CO₂",
  pmv: "Comfort",
  ca: "Regulation",
  // Quality-lamp level vocabulary (air_* reads backwards for percentages).
  pmv_ok: "OK",
  pmv_warn: "Fair",
  pmv_alert: "Low",
  ca_ok: "OK",
  ca_warn: "Reduced",
  ca_alert: "Poor",
  pmv_not_validated: "not validated (outside ISO 7730)",
  // ADR-0069 E7: active-comfort measure line.
  ac_active: "Comfort active",
  ac_fan: "fan first",
  ac_ce: "cool edge",
  ac_maturing: "maturing",
  ac_none: "no measure active",
  override_clamped: "Setpoint clamped",
  manual: "Manual",
  resume_schedule: "Resume schedule",
  valid_until: "valid until",
  instead_of: "instead of",
  norm_limit: "norm limit",
  permanent: "permanent",
  operative: "operative",
  air: "air",
  cools: "cooling",
  heats: "heating",
  dries: "drying",
  origin_device: "device",
  origin_app: "app",
  compressor_guard: "Compressor guard",
  mould: "Mould limit",
  binding_mold: "Mould guard holds the minimum",
  binding_frost: "Frost guard holds the minimum",
  mode_off: "Off",
  mode_heat: "Heating",
  mode_cool: "Cooling",
  mode_dry: "Drying",
  mode_fan_only: "Fan",
  presets: "Presets",
  air_quality: "Room condition",
  air_ok: "OK",
  air_warn: "Elevated",
  air_alert: "Critical",
  vent_open: "Air out",
  vent_mold_risk: "mould risk",
  vent_moisture_out: "moisture",
  vent_co2: "CO₂",
  vent_heat_out: "cooler outside",
};
const DE: Dict = {
  in_band: "Im Komfortband",
  cool_edge: "Untere Bandkante",
  warm_edge: "Obere Bandkante",
  below: "Unter dem Komfortband",
  above: "Über dem Komfortband",
  unknown: "Kein Messwert",
  preheating: "Vorheizen",
  coasting: "Auslaufen",
  window: "Fenster offen",
  window_auto: "Fenster (auto)",
  bypass: "Fenster-Erkennung aus",
  eco: "Eco",
  comfort: "Komfort",
  boost: "Boost",
  away: "Abwesend",
  failure: "Heizausfall",
  learning: "Lernt",
  shadow: "Shadow aktiv",
  setpoint: "Sollwert",
  no_entity: "Bitte eine Poise-Thermostat-Entität wählen.",
  min_left: "Min",
  no_system: "Bitte den Poise-System-Sensor wählen.",
  sys_title: "Poise System",
  demand_on: "Kesselbedarf",
  demand_off: "Kein Bedarf",
  frost: "Frost-Override",
  zones: "Zonen",
  heating_n: "heizen",
  flow: "Vorlauf",
  shed: "abgeworfen",
  shadow_would: "würde",
  update_msg: "Neue Poise-Karten-Version verfügbar — zum Aktualisieren neu laden.",
  reload: "Neu laden",
  details: "Details anzeigen",
  temperature: "Temperatur",
  humidity: "Feuchte",
  co2: "CO₂",
  pmv: "Behaglichkeit",
  ca: "Regelgüte",
  // Güte-Lampen-Vokabular („Erhöht" liest sich für Prozente falsch herum).
  pmv_ok: "OK",
  pmv_warn: "Mäßig",
  pmv_alert: "Gering",
  ca_ok: "OK",
  ca_warn: "Eingeschränkt",
  ca_alert: "Schlecht",
  pmv_not_validated: "nicht validiert (außerhalb ISO 7730)",
  // ADR-0069 E7: Maßnahmen-Zeile der Aktiven Behaglichkeit.
  ac_active: "Behaglichkeit aktiv",
  ac_fan: "Lüfter zuerst",
  ac_ce: "Kühlkante",
  ac_maturing: "reift",
  ac_none: "keine Maßnahme aktiv",
  override_clamped: "Sollwert geklemmt",
  manual: "Manuell",
  resume_schedule: "Zeitplan fortsetzen",
  valid_until: "gilt bis",
  instead_of: "statt",
  norm_limit: "Normgrenze",
  permanent: "dauerhaft",
  operative: "operativ",
  air: "Luft",
  cools: "kühlt",
  heats: "heizt",
  dries: "entfeuchtet",
  origin_device: "Gerät",
  origin_app: "App",
  compressor_guard: "Verdichterschutz",
  mould: "Schimmelgrenze",
  binding_mold: "Schimmelschutz hält die Untergrenze",
  binding_frost: "Frostschutz hält die Untergrenze",
  mode_off: "Aus",
  mode_heat: "Heizen",
  mode_cool: "Kühlen",
  mode_dry: "Entfeuchten",
  mode_fan_only: "Lüfter",
  presets: "Voreinstellungen",
  air_quality: "Raumzustand",
  air_ok: "OK",
  air_warn: "Erhöht",
  air_alert: "Kritisch",
  vent_open: "Lüften",
  vent_mold_risk: "Schimmelrisiko",
  vent_moisture_out: "Feuchte",
  vent_co2: "CO₂",
  vent_heat_out: "draußen kühler",
};

export function t(lang: string | undefined, key: string): string {
  const dict = (lang ?? "en").toLowerCase().startsWith("de") ? DE : EN;
  return dict[key] ?? EN[key] ?? key;
}
