type Dict = Record<string, string>;

const EN: Dict = {
  in_band: "In comfort band",
  cool_edge: "Cool edge of band",
  warm_edge: "Warm edge of band",
  below: "Below comfort band",
  above: "Above comfort band",
  unknown: "No reading",
  preheating: "Pre-heating",
  coasting: "Coasting",
  window: "Window open",
  window_auto: "Window (auto)",
  bypass: "Window detection off",
  eco: "Eco",
  comfort: "Comfort",
  boost: "Boost",
  away: "Away",
  failure: "Heating failure",
  learning: "Learning",
  shadow: "Shadow active",
  setpoint: "Setpoint",
  no_entity: "Select a Poise thermostat entity.",
  min_left: "min",
  no_system: "Select the Poise System sensor.",
  sys_title: "Poise System",
  demand_on: "Boiler demand",
  demand_off: "No demand",
  frost: "Frost override",
  zones: "zones",
  heating_n: "heating",
  flow: "Flow",
  shed: "shed",
  shadow_would: "would",
  update_msg: "New Poise card version available — reload to update.",
  reload: "Reload",
  details: "Show details",
  temperature: "Temperature",
  humidity: "Humidity",
  co2: "CO₂",
  air_quality: "Room condition",
  air_ok: "OK",
  air_warn: "Elevated",
  air_alert: "Critical",
};
const DE: Dict = {
  in_band: "Im Komfortband",
  cool_edge: "Untere Bandkante",
  warm_edge: "Obere Bandkante",
  below: "Unter dem Komfortband",
  above: "Über dem Komfortband",
  unknown: "Kein Messwert",
  preheating: "Vorheizen",
  coasting: "Auslaufen",
  window: "Fenster offen",
  window_auto: "Fenster (auto)",
  bypass: "Fenster-Erkennung aus",
  eco: "Eco",
  comfort: "Komfort",
  boost: "Boost",
  away: "Abwesend",
  failure: "Heizausfall",
  learning: "Lernt",
  shadow: "Shadow aktiv",
  setpoint: "Sollwert",
  no_entity: "Bitte eine Poise-Thermostat-Entität wählen.",
  min_left: "Min",
  no_system: "Bitte den Poise-System-Sensor wählen.",
  sys_title: "Poise System",
  demand_on: "Kesselbedarf",
  demand_off: "Kein Bedarf",
  frost: "Frost-Override",
  zones: "Zonen",
  heating_n: "heizen",
  flow: "Vorlauf",
  shed: "abgeworfen",
  shadow_would: "würde",
  update_msg: "Neue Poise-Karten-Version verfügbar — zum Aktualisieren neu laden.",
  reload: "Neu laden",
  details: "Details anzeigen",
  temperature: "Temperatur",
  humidity: "Feuchte",
  co2: "CO₂",
  air_quality: "Raumzustand",
  air_ok: "OK",
  air_warn: "Erhöht",
  air_alert: "Kritisch",
};

export function t(lang: string | undefined, key: string): string {
  const dict = (lang ?? "en").toLowerCase().startsWith("de") ? DE : EN;
  return dict[key] ?? EN[key] ?? key;
}
