"""Deterministic real-trace replay (ADR-0011 harness, ADR-0014 determinism).

Re-drives a fresh estimator from a recorded field trace: the same trace always
yields the same model, so a golden trace's learned model can be reproduced
offline, and candidate algorithms (e.g. the tau-settle detector, CA thresholds)
can be scored against real trajectories instead of only the synthetic RC plant.
Unlike ``replay.py`` (forward-simulation against ``RCPlant``), this consumes
*recorded* ticks — the drive inputs are data, not generated by a plant.
"""

from __future__ import annotations

from collections.abc import Sequence

from custom_components.poise.estimation.thermal_ekf import ThermalEKF, ThermalModel
from custom_components.poise.trace.schema import (
    TraceRecord,
    is_supported_version,
)


def load_trace(text: str, *, drop_unsupported: bool = True) -> list[TraceRecord]:
    """Parse a JSONL trace (one ``TraceRecord`` per non-blank line).

    Version-aware (deprecation): records whose ``v`` falls outside the supported
    window (``MIN_SUPPORTED_TRACE_VERSION``..``TRACE_VERSION``) are skipped when
    ``drop_unsupported`` (the default), so a future schema bump can retire an old
    golden without the loader choking on its records.
    """
    out: list[TraceRecord] = []
    for ln in text.splitlines():
        if not ln.strip():
            continue
        rec = TraceRecord.from_json_line(ln)
        if drop_unsupported and not is_supported_version(rec.v):
            continue
        out.append(rec)
    return out


def replay_ekf(records: Sequence[TraceRecord]) -> ThermalModel:
    """Drive a fresh EKF from the trace's per-tick inputs; return the final model.

    Deterministic: identical records -> identical model (ADR-0014). ``dt`` comes
    from consecutive ``mono`` stamps; the first record only anchors the state
    temperature (no step), mirroring a cold estimator meeting its first sample.
    """
    ekf = ThermalEKF()
    if records:
        ekf.x[0] = records[0].room
    prev_mono: float | None = None
    for r in records:
        if prev_mono is not None:
            dt_h = (r.mono - prev_mono) / 3600.0
            if dt_h > 0.0:
                ekf.predict(
                    dt_h,
                    t_out=r.t_out,
                    u_h=r.u_h,
                    u_c=r.u_c,
                    q_solar=r.q_solar,
                    q_occ=r.q_occ,
                )
                ekf.update(r.room)
        prev_mono = r.mono
    return ekf.get_model()
